name: linting, testing, building
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 17.x ]
    steps: 
      - uses: actions/checkout@v3
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm i --force
      - name: build production project
        run: npm run build:prod
        if: always()
      - name: lint ts
        run: npm run lint:ts
        if: always()
      - name: stylelint
        run: npm run lint:scss
      - name: unit tests
        run: npm run test:unit
        if: always()
      - name: build storybook
        run: npm run storybook:build
        if: always()
      - name: screenshot & storybook tests
        run: npm run test:ui:ci
        if: always()

